### ISSUE TITLE
Structure responses properly

### ISSUE THREAD

**Issue by alanansari** [AVtheking/Udemy-backend#5]
Like this:

{
success: true/false,
msg: "Some message sent for the use of frontend",
data : {
key: "object containing multiple key value pairs for data"
}
}

<img width="267" alt="image" src="https://github.com/AVtheking/Ilearn-backend/assets/22475370/da0bd05d-0ef3-4b38-a654-6ff74379460c">

**Comment by AVtheking** [comment]
done
